meta-llama/Llama-3.3-70B-Instruct added as validated model
quic/efficient-transformers pull request #196
Opened 2024-12-10 09:52 UTC by abukhoy

2024-12-10 10:16 UTC, ochougul requested changes
Please add a dropdown for all the updates except first 5

2024-12-11 08:34 UTC, abukhoy commented
Readme drop down is added now.

2024-12-11 09:16 UTC, ochougul approved these changes

2024-12-11 09:22 UTC, quic-rishinr approved these changes

2024-12-11 10:14 UTC, merged