Code for SDK configs Inclusion
quic/efficient-transformers pull request #203
Opened 2024-12-20 10:30 UTC by abukhoy

This will create a config JSON file, which contains all the details about compilation and SDK versions.

Currently, this code is added in the code block of QEFFAutoModelForCausalLM.compile.

The config would look like below:

```
{
    "huggingface_config": "hf stuff",
    "qpc_config": {
        "QEff_config": {
            "pytorch_transforms": "...",
            "onnx_transforms": "...",
            "onnx_path": "..."
        },
        "compilation_config": {
            "compile_dir": "...",
            "specializtions_file_path": "...",
            "apps_sdk_version": "..."
        }
    }
}
```

Note: The code structure may change.

2025-01-15 04:16 UTC, quic-rishinr requested changes

2025-01-15 04:16 UTC, quic-rishinr commented on QEfficient/transformers/models/modeling_auto.py
> +        qconfig_file_path = os.path.join(os.path.dirname(self.qpc_path), "qconfig.json")
Do we need to extract these information here? Wouldnt it be better to extract this information inside create_and_dump_config method?

2025-01-15 04:16 UTC, quic-rishinr commented on QEfficient/utils/_utils.py
> +    yaml_file_path = os.path.join(os.getenv(QnnConstants.QNN_SDK_PATH_ENV_VAR_NAME), "sdk.yaml")
if QNN sdk is not set this would throw an error. This needs to be handled. Additionally, please ensure that variable names are defined clearly for yaml_file_path and yaml_data

2025-01-15 04:16 UTC, quic-rishinr commented on QEfficient/utils/constants.py
> +    SDK_APPS_XML = tree = "/opt/qti-aic/versions/apps.xml"  # This xml file is parsed to find out the SDK version.
Can we remove tree variable name?

2025-01-16 10:28 UTC, quic-amitraj commented on QEfficient/transformers/models/modeling_auto.py
> +        except Exception as e:
Is there need of try and except here? Can we remove this?

2025-01-16 10:30 UTC, abukhoy commented on QEfficient/transformers/models/modeling_auto.py
> +        except Exception as e:
@quic-rishinr suggested to do it.

2025-01-20 06:38 UTC, quic-rishinr requested changes

2025-01-20 06:38 UTC, quic-rishinr commented on QEfficient/utils/_utils.py
> +        print(f"Failed to open XML File {Constants.SDK_APPS_XML}: {e}")
use logger warning instead of print statement.

2025-01-20 10:49 UTC, abukhoy commented on QEfficient/transformers/models/modeling_auto.py
> +            print(f"Failed to create the qconfig file: {e}")
@quic-rishinr logger warning?

2025-01-20 11:41 UTC, quic-rishinr commented on QEfficient/transformers/models/modeling_auto.py
> +            print(f"Failed to create the qconfig file: {e}")
yes

2025-01-28 07:58 UTC, ochougul requested changes
Also rebase

2025-01-28 07:58 UTC, ochougul commented on QEfficient/transformers/models/modeling_auto.py
> +        try:
remove try-except let it fail in case of any exception

2025-01-28 07:58 UTC, ochougul commented on QEfficient/transformers/models/modeling_auto.py
> +                onnx_path,
`self.qpc_path`
`self.onnx_path`

2025-01-28 07:58 UTC, ochougul commented on QEfficient/transformers/models/modeling_auto.py
> +                huggingface_config,
directly pass instead of creating a variable `self.model.config.__dict__`

2025-01-28 07:58 UTC, ochougul commented on QEfficient/transformers/models/modeling_auto.py
> +                onnx_transforms,
directly pass instead of creating variables

2025-01-28 07:58 UTC, ochougul commented on QEfficient/utils/__init__.py
> +    create_and_dump_qconfigs,
remove

2025-01-28 07:58 UTC, ochougul commented on QEfficient/utils/_utils.py
> +        qaic_version = None
remove try/except

2025-01-28 07:58 UTC, ochougul commented on QEfficient/utils/_utils.py
> +            qnn_sdk_details = None
remove try/except

2025-01-28 07:58 UTC, ochougul commented on QEfficient/utils/_utils.py
> +    def make_serializable(obj):
Is this method required? Can you please explain where creating json fails if we don't call this?

2025-01-28 09:00 UTC, ochougul commented
Also, the dumped config should either have compiler config change this to `aic_compiler_config` or `qnn_config` if user compiles via qnn then only qnn_config should be dumped otherwise only compiler config should be dumped.

2025-01-29 09:23 UTC, abukhoy commented on QEfficient/utils/__init__.py
> +    create_and_dump_qconfigs,
If we remove this, How Can we able to access this method from `modelling_auto.py` ?

2025-01-29 09:38 UTC, abukhoy commented on QEfficient/utils/_utils.py
> +    def make_serializable(obj):
Removed.

2025-02-26 13:05 UTC, abukhoy commented on QEfficient/utils/_utils.py
> +    def make_serializable(obj):
It is needed now.

2025-02-27 06:12 UTC, quic-rishinr requested changes

2025-02-27 06:12 UTC, quic-rishinr commented on QEfficient/base/modeling_qeff.py
> +            pass
its better to keep the model_config as None if new architecture comes.

2025-02-27 06:12 UTC, quic-rishinr commented on QEfficient/utils/_utils.py
> +        "huggingface_config": make_serializable(huggingface_config),
Better to add it this way
"huggingface_config": make_serializable(huggingface_config) if huggingface_config else None,

2025-02-27 06:25 UTC, abukhoy commented on QEfficient/utils/_utils.py
> +        "huggingface_config": make_serializable(huggingface_config),
make_serilizable will handle this. Do I need to add this extra "if" statement?

2025-02-27 08:27 UTC, ochougul commented on QEfficient/utils/_utils.py
> +    }
Don't always dump both qnn_config and aic_compiler_config. Either one of them should only be dumped based on if it was using qnn_compile or normal compile

2025-02-27 09:44 UTC, quic-amitraj requested changes

2025-02-27 09:44 UTC, quic-amitraj commented on QEfficient/base/modeling_qeff.py
> +            model_config = self.model.config.__dict__
Please add this inside a decorator, so whole part of dumping will go inside the decorator and will make this function clean.

2025-02-27 09:44 UTC, quic-amitraj commented on QEfficient/base/modeling_qeff.py
> +            qnn_config=qnn_config,
Same for this as well, use the same decorator for this as well.

2025-02-27 10:17 UTC, quic-amitraj commented on QEfficient/utils/_utils.py
> +            return make_serializable(obj.__dict__)
instead of `obs.__dict__` better you can use `vars(obj)`.Refer- [why](https://stackoverflow.com/questions/21297203/use-dict-or-vars)

2025-02-27 10:17 UTC, quic-amitraj commented on QEfficient/utils/_utils.py
> +        else:
No need of this else condition.

2025-02-27 12:31 UTC, abukhoy commented on QEfficient/utils/_utils.py
> +    }
Yes, I am not dumping always. You can see the below code.

2025-02-27 12:49 UTC, abukhoy commented on QEfficient/utils/_utils.py
> +        else:
It is needed. suppose JSON does not support "torch.float32", So it will create an error. And if we do not write else here, then we would get "null" in the json.

2025-02-28 08:57 UTC, quic-rishinr commented on QEfficient/utils/_utils.py
> +    }
if it will be handled no need for if condition.

2025-02-28 08:58 UTC, quic-rishinr commented on QEfficient/utils/_utils.py
> +        "huggingface_config": make_serializable(huggingface_config),
it will return a string of None right? ok no need to add if statement.

2025-03-03 14:38 UTC, quic-amitraj approved these changes
LGTM

2025-03-03 14:59 UTC, merged